import { Edge } from "../items/ttr_defs";

abstract class PushPopModel {
    source: string;

    constructor(source: string, ...kwargs: any[]) {
        this.source = source;
    }

    push(node: string, edges: Edge[], ...kwargs: any[]): void {
        /**
         * push a node with related edges
         * @param node: the pushed node
         * @param edges: the edges related to the pushed node
         * @param kwargs: the pushing context keyword arguments, generated by the pop operation
         * @return:
         */
        throw new Error("Method not implemented.");
    }
    pop(): [string | null, Record<string, any>] {
        /**
         * pop a node for the next step
         * @return: the popped node and its context
         */
        throw new Error("Method not implemented.");
    }

    get_context_snapshot(): Record<string, any> {
        /**
         * Get a snapshot dict for the strategy params
         * @return:
         */
        throw new Error("Method not implemented.");
    }

    get_node_rank(): Record<string, number> {
        /**
         * Get a node rank dict for the strategy
         * @return:
         */
        throw new Error("Method not implemented.");
    }
}

export {
    PushPopModel,
}
